export const ErrorCode = {
  //   OK: 1000,
  CANNOT_CONNECT_TO_DB: 1001,
  PARAMETER_IS_NOT_ENOUGH: 1002,
  PARAMETER_TYPE_IS_INVALID: 1003,
  PARAMETER_VALUE_IS_INVALID: 1004,
  UNKNOWN_ERROR: 1005,
  FILE_SIZE_IS_TOO_BIG: 1006,
  UPLOAD_FILE_FAILED: 1007,
  MAXIMUM_NUMBER_OF_IMAGE: 1008,
  NOT_ACCESS: 1009,
  ACTION_HAS_BEEN_DONE_PREVIOUSLY_BY_THIS_USER: 1010,
  COULD_NOT_PUBLISH_THIS_POST: 1011,
  LIMIT_ACCESS: 1012,
  NOT_ENOUGH_COINS: 9991,
  POST_IS_NOT_EXIST: 9992,
  CODE_VERIFY_IS_INCORRECT: 9993,
  NO_DATA_OR_END_OF_LIST_DATA: 9994,
  USER_IS_NOT_VALIDATED: 9995,
  USER_EXISTED: 9996,
  METHOD_IS_INVALID: 9997,
  TOKEN_IS_INVALID: 9998,
  EXCEPTION_ERROR: 9999,
};
type TErrorCode = typeof ErrorCode;
export type TErrorResponse = {
  code: TErrorCode[keyof TErrorCode];
  message: string;
};

export type TResponse<TData = undefined> = {
  errCode: number;
  message: string;
  data: TData;
};
